### ISSUE TITLE
Change node keys

### ISSUE THREAD

**Issue by hector-crean** [graphology/graphology#153]
Perhaps I've misread the documentation, but is there a way to reindex node keys easily -- other than creating a SerialisedGraph, and reindexing via the SerializedNode.key? Obviously node keys are by default strings, but often we may want to assign numerical values as keys. If we form a subset of this graph, we may want to reindex the keys to start form 0->numberOf(nodes)....

**Comment by Yomguithereal** [comment]
Hello @hector-crean. You can consider this graph implementation as a dict or Map. As such, you cannot change a node's key. You can just delete the node from the graph and readd it using another key. Something like:

```js
const attr = graph.getNodeAttributes(key);
graph.dropNode(key);
graph.addNode(key, attr);
```

But I understand why it can be a hassle if you also have to mind the edges while doing so. I can briefly check the underlying data structure to see if we could easily add a method to "re-key" a node.

> If we form a subset of this graph, we may want to reindex the keys to start form 0->numberOf(nodes)....

In this precise case, since you will create a new graph anyway, why can't you just reindex the keys prior to adding the node by keeping an incremental counter and newkey -> oldkey index while doing so?

**Comment by hector-crean** [comment]
@Yomguithereal  Many thanks! Very useful

**Comment by Yomguithereal** [comment]
@jacomyal @hector-crean @sim51 how about `#.renameNode`? Is the name ok? Should this be added? I can attest it can be implemented under the hood more efficiently than a succession of `#.dropNode` > `#.addNode` (and you won't have to handle the edges since it will be taken care of for you). Also the method should of course throw if you give a new key that already exist in the graph.
