### ISSUE TITLE
Most efficient way of constructing graph?

### ISSUE THREAD

**Issue by deklanw** [graphology/graphology#184]
I'm creating a function to ingest a certain graph format https://graph-tool.skewed.de/static/doc/gt_format.html

In my profiling it seems like adding edges one by one with `graph.addEdge(nodeIndex, neighbor);` is the bottleneck for a graph with 6k nodes and 178k edges. Is there a faster way in particular to add edges?

**Comment by Yomguithereal** [comment]
Hello @deklanw. Currently there is no obvious faster method than what you are doing. Is your code open source somehow so I can profile on my end? This said, I was discussing unsafe methods at some points to speed up edge addition in some case but I don't expect to win more than 10-20% boost on the existing. I am not opposed to creating specialized builders at some point to improve on this but can you describe some things a bit more: do you have the guarantee to process edges by source node adjacency, for instance, or are you processing them completely at random?

**Comment by deklanw** [comment]
Thanks for the quick reply!

> do you have the guarantee to process edges by source node adjacency, for instance,

Yes, exactly that.

>  Is your code open source somehow so I can profile on my end?

Sure, https://github.com/deklanw/graphology-gt

Just run
```
yarn
yarn test
```

The benchmarks aren't proper, I just sprinkled `performance.now` and `console.log` throughout the code and ran the tests. I also intend to run this in the browser not Node in the end, so it's not perfectly representative.


Here are results for largest graph I'm testing
```
  {
    name: "us_agencies",
    numNodes: 42951,
    numEdges: 506873,
    directed: true,
  },
```
```
    us_agencies
    Adding nodes took 18.882299999999987
    Parsing binary and adding edges took total time 2206.0173000000004
    Just all addEdgeWithKey calls took 1846.4166999998472
    Adding props took 885.6346000000003
    Total time to create graph 3134.7184000000007
```

3.1s for a graph that large is obviously not bad at all, but I'm still interested to see if it can be improved.

More graphs in `gt` format, compressed with zstd can be obtained here https://networks.skewed.de/

**Comment by Yomguithereal** [comment]
I have thought of two *funny* optimizations that could speed up your use case without requiring you to change the code. I will try to implement them soon. Also do I have the permission to make comments over some parts of your code to help you speed it up a little bit?

**Comment by deklanw** [comment]
More than permission :P

**Comment by Yomguithereal** [comment]
Ok so I tried several things but nothing really improved performance:

1. Since you process nodes by adjacency I tried to internally cache the last accessed source node to avoid hashmap lookups but it seems most JS engines already have this kind of optimization baked in so it did nothing apart from making the code harder to understand
2. I tried to avoid testing the pre-existence of an edge's key in the graph to avoid a lookup in some cases but this did not yield significant improvements neither

What I understood from those attemps is that what's dominating runtime is in fact setting the edge's data in the internal hashmap and unfortunately I can't do much about this :( (I have some ideas but they may be suboptimal). The good news is that recent version of v8 and Gecko have largely improved this and I have performance boosts up to 100% from node v12 to node v15 or a recent Chrome for instance.

**Comment by Yomguithereal** [comment]
On a side note @deklanw, will you want to include your library to graphology's standard lib at one point? I can add you to the org and move your repo to it, if you so desire.

**Comment by deklanw** [comment]
> What I understood from those attemps is that what's dominating runtime is in fact setting the edge's data in the internal hashmap and unfortunately I can't do much about this :( (I have some ideas but they may be suboptimal). The good news is that recent version of v8 and Gecko have largely improved this and I have performance boosts up to 100% from node v12 to node v15 or a recent Chrome for instance.

Ah, well thanks for trying anyway. It's pretty fast anyway.

> will you want to include your library to graphology's standard lib at one point? I can add you to the org and move your repo to it, if you so desire

Sure, if you think it's useful. I just spruced it up a bit. Dunno about putting it on npm

Btw, why are the TS types in a separate package? Never seen officially maintained types in a separate package

**Comment by Yomguithereal** [comment]
> Btw, why are the TS types in a separate package? Never seen officially maintained types in a separate package

That's because `graphology` is first and foremost a specification for a Graph object in JavaScript and this repo only contains a reference implementation. But there exist other implementations of the specs in the wild because there is no silver bullet way to implement a graph, you always have tradeoffs and decisions to make. For instance, some companies use their own implementations that don't require neighbor indexation, for instance, so they are optimized for specific use cases. Thus, you'll see that no single lib from the standard lib actually has the reference implementation as a dependency and it's the same rationale for the typings so that each implementation may reuse them directly.

**Comment by deklanw** [comment]
Thanks. Makes sense.

**Comment by deklanw** [comment]
@Yomguithereal published onto npm. I think it's good enough to move into the repo now, if you want

**Comment by Yomguithereal** [comment]
Hello @deklanw, I think your library would be a useful addition to graphology standard library indeed. Let me invite you to the org. Then if you want you can transfer the repo to the org and I will give you full rights over it. However would you be open to a PR from me to align your API with what's currently already existing regarding parsers for graphology, so that everything remains consistent?
