### ISSUE TITLE
Add safeguards to attributes setters

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology#33]
Example:

```js
graph.setNodeAttribute(node, {age: 17});
// Will produce silly things
```

**Comment by luccitan** [comment]
Hello,

Adding a safeguard for the node attribute setter is not a problem. 

Safeguarding the attribute setting action for the edges is a problem though. I consider calling the setter parallel to your exemple for the node, that is :

`graph.setEdgeAttribute('John', 'Martha', { age: 17})`

Since there are only 3 arguments, the dynamic method pattern used will consider this is a node setter despite the good arguments at the creation and thus it will look for a `John` edge instead of a `Source: John`-`Target: Martha` edge. 
An incoherent `NotFoundGraphError` will be thrown, whereas an `InvalidArgumentsGraphError` is awaited. 

I can submit a PR for the little node attribute setter, plus the commented test about the edge attribute setter if wanted
