### ISSUE TITLE
Provide generic change event

### ISSUE THREAD

**Issue by sushantdhiman** [graphology/graphology#348]
**Problem**

Is it possible to subscribe to any change in graph instance? I am looking for generic `change` event, rather than subscribing to all events like `nodeAdded, edgeAdded ...etc`

**Background**

In my web application, I would like to change application state when graph instance changes e.g. adding new node. Currently I need to subscribe to all events and update application state based upon those event.

**Comment by Yomguithereal** [comment]
Hello @sushantdhiman, I see your point but I don't currently want to add such an event for performance reasons (emitting two events per action on my side would have a slight perf hit I don't want to pay). What's more this can very easily be implemented in userland by creating a tiny user function. I also don't want to edit the graph's event emitter to enable you to listen to all events with a single listeners because I want to stick to node's standard event emitter. So for the time being my answer is no.

See an example of such a helper function:

```js
const EVENT_NAMES = ['nodeAdded', 'edgeAdded', ...];

function listenToAll(graph, listener) {
  const wrappers = EVENT_NAMES.map(function (name) {
    function wrapper(payload) {
      listener(name, payload);
    }
    graph.on(name, wrapper);

    return [name, wrapper];
  });

  return () => {
    wrappers.forEach((name, wrapper) => {
      graph.removeListener(name, wrapper);
    });
  };
}

const removeListeners = listenToAll(graph, (eventName, payload) => {
  console.log(eventName, payload);
});
```

**Comment by sushantdhiman** [comment]
Hi @Yomguithereal, Thanks I have already implemented something similar to what you have suggested.

Will it be possible to expose all possible event names programmatically, so I don't have to keep looking at documentation if any event was added or removed in future?

**Comment by Yomguithereal** [comment]
@sushantdhiman this could be a solution indeed, let met think about it. Another clever but hacky solution would also be to monkey patch the graph's emit method to emit the `changed` event before or after the regular one.
