### ISSUE TITLE
Error while serializing to gexf

### ISSUE THREAD

**Issue by kmalski** [graphology/graphology#396]
Hi, there is a small bug in [gexf writer](https://github.com/graphology/graphology/blob/master/src/gexf/common/writer.js#L462). If graph has `boolean` attribute then `XMLWriter` throws error, because he can not serialize this type. The workaround is easy, for example casting to string

**Comment by Yomguithereal** [comment]
You are right indeed. Casting to string means losing the idempotence between serialization and deserialization in this case but the gexf format does not allow for better anyway. Do you want to open a PR about this?

**Comment by kmalski** [comment]
I would say that this is still consitent, because that's the way in which node attributes are serialized (I mean, boolean attributes are just strings in resulting file, not sure how it works backward). Sure, I will create PR.

**Comment by Yomguithereal** [comment]
It's not consistent because gexf has no way to type graph metadata vs. node & edge attributes. Which mean if you serialize your boolean graph attribute to a string, you will parse it as a string when reading the file back, thus obliterating the original type. But the format does not allow better so I am prepared to live with this minor inconvenience and I prefer this to not emitting the attribute in the gexf file or getting an error.

**Comment by Yomguithereal** [comment]
@kmalski v0.10.2 of `graphology-gexf` is now live on npm
