### ISSUE TITLE
Is there a way to animate graph with ForceAtlas2 layout?

### ISSUE THREAD

**Issue by vishnusajev** [graphology/graphology#416]
Hi I would like to know if its possible to animate the graph rendered using ForceAtlas2 layout, just like the Force layout.

**Comment by Yomguithereal** [comment]
If you mean, displaying the iterations in the browser you can use [sigma.js](https://www.sigmajs.org/) for that yes. It works exactly the same way as the force layout by using the provided web worker. There is an example of this here: https://github.com/jacomyal/sigma.js/blob/4ce3ac9edb5762ba07e76083c8214176b872f316/examples/layouts/index.ts

**Comment by vishnusajev** [comment]
Hi @Yomguithereal, thanks for reaching out. What I meant was something similar to this example https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/mouse-manipulations. Here its renders using `graphology-layout-force` and it has an animation. You can also see it when we try drag a node, the entire graph moves and adjust itself. I was looking for something like that.

**Comment by Yomguithereal** [comment]
If you are looking specifically to run a layout algorithm while keeping the ability to drag and drop I advise you not to do it with FA2, as it has not been designed for this kind of usage. This is exactly why we created the simple force-layout.

This said, if you still want to do it, you can adjust the example you are pointing to use force atlas 2 instead and it should somehwat work since the supervisor APIs are near identical.

**Comment by vishnusajev** [comment]
@Yomguithereal But when I try to set the x and y attribute using `setNodeAttribute` it just resets to the earlier position
