### ISSUE TITLE
Not able to set the "key" attribute iteratively

### ISSUE THREAD

**Issue by wthrajat** [graphology/graphology#472]
For the example data
```
  "nodes": [
    {
      "key": "0",
      "attributes": {
        "size": 10
      }
  
      ...so on...
 ]
 ```
 
I can set, for example the size attribute for multiple nodes using the below method:
```
let j = 0;
graph.forEachNode((node) => {
  graph.setNodeAttribute(node, "size", 10);
  j++;
});
```
 
But I am unable to set the attribute `key` with the following approach:
```
let k = 0;
graph.forEachNode((node) => {
  graph.setNodeAttribute(node, "key", "k");
  k++;
});
``` 
I also tried
```
let k = 0;
graph.forEachNode(() => {
  graph.setAttribute("key", "k");
  k++;
});
```

But I get the error `InvalidArgumentsGraphError Graph.importNode: no key provided.`

**Comment by Yomguithereal** [comment]
The key of a node is not an attribute. Think of it like a key in an object or in a dictionary. It does not really make sense to change it because it is very important to keep it the same so that edges have correct source & target. This means you cannot easily change the key of a node, which is basically "renaming" it, and this is far from trivial because you need to ensure the new name is not already used and rewire the edges etc. What is your use case here exactly?

Still, if you understand what you are actually wanting to do here, `graphology-utils` packs a helper function that does just that: https://graphology.github.io/standard-library/utils#renamegraphkeys

**Comment by wthrajat** [comment]
Yes I get it what you're pointing to.
My goal is:
I want the graph data (`data.json` in my case) to contain least possible hard-coded details (like earlier I manually put the `"size": 10` in every node, and it was very tiresome to put the size manually on every nodes, hence I removed the `size` attribute from every node of my `data.json` file and then used this method to give the `"size": 10` to every node (just had to write 3 lines)
```
let j = 0;
graph.forEachNode((node) => {
  graph.setNodeAttribute(node, "size", 10);
  j++;
});
```

I want to do similar thing for key also. I need to find a method where I can initialize the key (`from 0 to n`, this way every key will be unique).

**Comment by Yomguithereal** [comment]
> I want to do similar thing for key also.

This only make sense if your graph has no edges. Else if you don't have keys for nodes in your data you won't be able to have edges pointing to something consistent and your data will basically be moot. Why don't you generate your graph data in the first place using a range of 0-n integer for node keys (before feeding data to a graphology instance), I don't understand, everything seems to be very circonvoluted in your examples. You basically have a problem with data processing, not graphology itself. What you describe would be like creating a dictionary with values but deciding what the keys will be afterwards, it does not make sense.

I think you need to go back to how you are actually generating (or wrangling) your json file in the first place and think about node keys and edges source & target there.

**Comment by wthrajat** [comment]
Hi. I fixed this issue. You were right I first needed to figure out how my dataset looks like.
Thanks again :)
